# Generated by Django 4.1.7 on 2023-03-19 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medimg', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='hamzat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
    ]
