# Generated by Django 4.1.7 on 2023-03-19 23:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medimg', '0003_quiz'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='hamzat',
            new_name='hichem',
        ),
    ]
