# Generated by Django 4.1.7 on 2023-03-19 23:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medimg', '0006_etudiant'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('text', models.TextField()),
                ('answer_1', models.CharField(default='default_value', max_length=255)),
                ('answer_2', models.CharField(default='default_value', max_length=255)),
                ('answer_3', models.CharField(default='default_value', max_length=255)),
                ('answer_4', models.CharField(default='default_value', max_length=255)),
                ('correct_answer', models.CharField(default='default_value', max_length=255)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='medimg.quiz')),
            ],
        ),
    ]
