# Generated by Django 4.1.7 on 2023-03-20 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medimg', '0007_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='correct_answer',
            field=models.CharField(default='correct_answer_default', max_length=255),
        ),
    ]
