# Generated by Django 4.1.7 on 2023-03-21 19:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medimg', '0008_alter_question_correct_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='answer_1',
            field=models.CharField(default='default_value1', max_length=255),
        ),
        migrations.AlterField(
            model_name='question',
            name='answer_2',
            field=models.CharField(default='default_value2', max_length=255),
        ),
        migrations.AlterField(
            model_name='question',
            name='answer_3',
            field=models.CharField(default='default_value3', max_length=255),
        ),
        migrations.AlterField(
            model_name='question',
            name='answer_4',
            field=models.CharField(default='default_value4', max_length=255),
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('is_correct', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='medimg.question')),
            ],
        ),
    ]
