# Generated by Django 4.1.7 on 2023-03-21 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medimg', '0009_alter_question_answer_1_alter_question_answer_2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='answer_1',
        ),
        migrations.RemoveField(
            model_name='question',
            name='answer_2',
        ),
        migrations.RemoveField(
            model_name='question',
            name='answer_3',
        ),
        migrations.RemoveField(
            model_name='question',
            name='answer_4',
        ),
        migrations.RemoveField(
            model_name='question',
            name='correct_answer',
        ),
    ]
