# Generated by Django 4.1.7 on 2023-03-22 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medimg', '0011_question_answer_1_question_answer_2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='duration',
            field=models.IntegerField(default=0),
        ),
    ]
