# Generated by Django 4.1.7 on 2023-03-23 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medimg', '0012_quiz_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professeur',
            name='module',
            field=models.CharField(choices=[('Radiographie', 'Radiographie'), ('Tomodensitométrie', 'Tomodensitométrie'), ('IRM', 'IRM'), ('Échographie', 'Échographie'), ('Scintigraphie', 'Scintigraphie'), ('Angiographie', 'Angiographie')], max_length=200, null=True),
        ),
    ]
