# Generated by Django 4.1.7 on 2023-03-26 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medimg', '0016_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='score_question',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
