# Generated by Django 4.1.7 on 2023-03-26 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medimg', '0017_question_score_question'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='score_question',
            new_name='points',
        ),
    ]
