# Generated by Django 4.1.7 on 2023-03-29 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medimg', '0019_alter_question_points'),
    ]

    operations = [
        migrations.CreateModel(
            name='amirouche',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cz', models.CharField(max_length=200)),
            ],
        ),
    ]
