# Generated by Django 4.1.7 on 2023-04-02 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medimg', '0020_amirouche'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='module',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
