# Generated by Django 4.1.7 on 2023-04-14 00:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medimg', '0022_quiz_total'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReponseEtudiant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reponse', models.CharField(max_length=100)),
                ('est_correcte', models.BooleanField(default=False)),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medimg.etudiant')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medimg.question')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medimg.quiz')),
            ],
        ),
    ]
