# Generated by Django 4.1.7 on 2023-04-14 01:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medimg', '0023_reponseetudiant'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=10)),
                ('is_correct', models.BooleanField(default=False)),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medimg.etudiant')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medimg.question')),
            ],
        ),
    ]
