# Generated by Django 4.1.7 on 2023-04-14 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medimg', '0024_studentanswer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reponseetudiant',
            old_name='est_correcte',
            new_name='correct',
        ),
        migrations.RemoveField(
            model_name='reponseetudiant',
            name='quiz',
        ),
        migrations.AlterField(
            model_name='reponseetudiant',
            name='reponse',
            field=models.CharField(max_length=255),
        ),
    ]
