# Generated by Django 4.1.7 on 2023-04-15 02:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('medimg', '0027_note_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='reponseetudiant',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
